apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template: # the template says how to create each individual pod that the deployment will manage
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: brandonshearin/tickets-auth
          env:
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets # there can be multiple db's inside a monogodb instance
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service # default behavior, when no type is provided, is to create a ClusterIP service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000